branches:
 only:
  - main
language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cd $TRAVIS_BUILD_DIR
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
 provider: script
 skip_cleanup: true
 script:
  - curl -T myAllocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ucnickol:$BINTRAY_API_KEY "https://api.bintray.com/content/cnickol/myAllocator/$TRAVIS_BUILD_NUMBER/myAllocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
 on:
  branch: main